### ISSUE TITLE
建议使用 submodule 管理子模块

### ISSUE THREAD

**Issue by wineee** [Raibows/NCEPU-CS-COURSES#17]

**Comment by wineee** [comment]
一个课设对应一个仓库，并用.gitmodules管理比较方便

**Comment by Raibows** [comment]
很好的想法，感谢建议！但是否会增加新手的使用成本呢？还需要讨论一下
@Leon-Francis

**Comment by wineee** [comment]
成本并不高，
第一步，创建自己的仓库并上传代码，这个是基础
第二步，向这个项目的.gitmodules文件添加3行
```bash
[submodule "Cryptography/CryptographyCalc"]       
path = Cryptography/CryptographyCalc        
url = https://github.com/wineee/CryptographyCalc.git
```
path和url换成自己的

**Comment by Raibows** [comment]
有一个问题是，如果主仓库依赖了其他人的仓库作为submodule，如果源submodule仓库进行了重大删改，新clone的人都会受之影响。且此影响不能提起得知，亦不能提前删除submodule配置。

一个可能的方案是，仍然采用submodule来配置整体结构，但**本地或公用帐号**fork一份submodule项目单元的源代码，这样是可控的。

**Comment by Leon-Francis** [comment]
> 一个课设对应一个仓库，并用.gitmodules管理比较方便

非常好的建议，只是我觉得其带来的优势不足以弥补额外的使用成本。

对于本项目，由于没有模块化开发需求，modules管理的优势在于

- 在只专注某一项目时可以不用clone其他项目文件
- 可以保证本地子项目和主项目同步更新

同时其弊端较为明显

- 子项目的每次更新都要求主项目提交修改以更新主项目指针，这是很大的额外成本
- 由于学校没有公共账号，本项目使用的是 @Raibows 的个人账号，而使用submodules管理要求其本地始终要有一份保持更新的主项目备份

不过以上仅是我个人的观点，而且抱着学习的目的来说我也希望能够尝试使用submodules管理，还是看你的意见了 @Raibows

**Comment by Leon-Francis** [comment]
> 有一个问题是，如果主仓库依赖了其他人的仓库作为submodule，如果源submodule仓库进行了重大删改，新clone的人都会受之影响。且此影响不能提起得知，亦不能提前删除submodule配置。
> 
> 一个可能的方案是，仍然采用submodule来配置整体结构，但**本地或公用帐号**fork一份submodule项目单元的源代码，这样是可控的。

对于这个问题，只要主项目在更新指针时检查一下子项目的更改是否合乎规范即可，只有子项目的修改的话主项目的指针依旧会指向那个旧的commit id

**Comment by Raibows** [comment]
> > 有一个问题是，如果主仓库依赖了其他人的仓库作为submodule，如果源submodule仓库进行了重大删改，新clone的人都会受之影响。且此影响不能提起得知，亦不能提前删除submodule配置。
> > 一个可能的方案是，仍然采用submodule来配置整体结构，但**本地或公用帐号**fork一份submodule项目单元的源代码，这样是可控的。
> 
> 对于这个问题，只要主项目在更新指针时检查一下子项目的更改是否合乎规范即可，只有子项目的修改的话主项目的指针依旧会指向那个旧的commit id

如果submodule对应的Repo被拥有人delete了，那就会受到无法控制的影响。这样除了本地或公有帐号fork备份一份外，还有其他解决方案吗？我对submodule的一些机制比较小白。

**Comment by Leon-Francis** [comment]
> > > 有一个问题是，如果主仓库依赖了其他人的仓库作为submodule，如果源submodule仓库进行了重大删改，新clone的人都会受之影响。且此影响不能提起得知，亦不能提前删除submodule配置。
> > > 一个可能的方案是，仍然采用submodule来配置整体结构，但**本地或公用帐号**fork一份submodule项目单元的源代码，这样是可控的。
> > 
> > 
> > 对于这个问题，只要主项目在更新指针时检查一下子项目的更改是否合乎规范即可，只有子项目的修改的话主项目的指针依旧会指向那个旧的commit id
> 
> 如果submodule对应的Repo被拥有人delete了，那就会受到无法控制的影响。这样除了本地或公有帐号fork备份一份外，还有其他解决方案吗？我对submodule的一些机制比较小白。

我没有实际使用submodule管理过项目，这些只是我在网上查阅的教程中学习的。如果 @wineee 有过实际管理经验的话来回答更为合适。
在子项目远程仓库更新后，在主项目中进入到子模块通过`git pull`来拉取子项目的更新，如果不执行拉取，那么子项目的任何更新都不会影响主项目中子模块的代码。这样就算子项目对应的repo被delete，主项目不能再从原来的子项目拉取任何更新，原本已有的内容不会受到影响。

**Comment by wineee** [comment]
> * 子项目的每次更新都要求主项目提交修改以更新主项目指针，这是很大的额外成本

关于更新的问题，因为这个Repo是“收集和分享课设和实验代码”，实验验收后几乎不会有更新，推荐只收录已经完成的项目，而不是写了一半，这样也方便质量控制。

当然，如果确实需要更新，对方只要管好自己的repo就行，这里可以用 `git submodule foreach git pull` 

对于Repo被拥有人delete的问题：
首先一个主项目中引入了Submodule其实Git做了3件事情：
- 记录引用的仓库
- 记录主项目中Submodules的目录位置
- 记录引用Submodule的commit id
那么，对应的repo被delete, 理论上这里无法正常使用（这种情况我也没见过），我认为是否分享的权力在作者，如果ta不想分享，这里也不应保留。唯一的问题是作者会不会忘了删除这里的Submodule，不过这种情况应该很少出现

**Comment by wineee** [comment]
另外不需要全部Submodules化，只有2，3个文件的小项目可以保持原样

**Comment by Raibows** [comment]
> 那么，对应的repo被delete, 理论上这里无法正常使用（这种情况我也没见过），我认为是否分享的权力在作者，如果ta不想分享，这里也不应保留。

我觉得在提交至此Repo前是自由的，但提交之后，删除代码的权力就应该归属到社区了，而不仅仅是原owner随意决定了。如果提交了，未经通知、公告下，某天就突然删除了，这种变动应该不是一种很好的体验。
